server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:worddb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
